### ISSUE TITLE
rogue /div on website page

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#72]
This was probably my fault....

![image](https://user-images.githubusercontent.com/13010867/66622610-55594600-ebb6-11e9-8cfe-956448825ec6.png)

**Comment by dmbaker90** [comment]
Fixed.  There are 2 identical pages now for the mywebiste page.  One for the easter egg and one for the projects.  We could probably consolidate if it matters.

**Comment by YasmeenAlmuhanna** [comment]
Consolidating would be better. Not sure how to do that though.

**Comment by dmbaker90** [comment]
I consolidated them so both links go to the project markdown file now

**Comment by YasmeenAlmuhanna** [comment]
I still see two markdown pages in Atom. Is this what it is supposed to look like? 

![image](https://user-images.githubusercontent.com/13010867/66708937-6ecdcf80-ed27-11e9-92da-dd24e41eafa1.png)

**Comment by YasmeenAlmuhanna** [comment]
It might have been my fault though cuz I pushed an edit before pulling from the origin :/
